Release 1.0.0
owncloud/openidconnect pull request #116
Opened 2020-10-29 16:15 UTC by jnweiger

Closes #66

2020-10-29 16:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/openidconnect?pullRequest=116) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/openidconnect?pullRequest=116) before we can accept your contribution.<br/>**0** out of **3** committers have signed the CLA.<br/><br/>:x: pmaier1<br/>:x: jnweiger<br/>:x: HanaGemela<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/openidconnect?pullRequest=116) it.</sub>

2020-10-29 17:00 UTC, DeepDiver1975 requested changes
please review comment ...

git history looks a bit unclean as well ....

2020-11-06 08:50 UTC, micbar commented on lib/Sabre/OpenIdSabreAuthBackend.php
> +			try {
np. This was merged to master after the release. The release branch will not be rebased.
Just merged.

2020-11-06 08:54 UTC, DeepDiver1975 commented on lib/Sabre/OpenIdSabreAuthBackend.php
> +			try {
I am sorry - but I'll not merge this unclean commit history to master. :+1:

2020-11-06 08:55 UTC, phil-davis commented on lib/Sabre/OpenIdSabreAuthBackend.php
> +			try {
Demo of rebase in PR #120 - this code will "disappear" on merge, because it already exists the same in `master`

2020-11-06 08:58 UTC, micbar commented on lib/Sabre/OpenIdSabreAuthBackend.php
> +			try {
yes. Ready to merge, we did this a lot of times, the unclear history will just disappear.
GitHub UI is not always getting what we do 😄

2020-11-06 09:03 UTC, DeepDiver1975 commented on lib/Sabre/OpenIdSabreAuthBackend.php
> +			try {
ok - can you in the furture make sure that people use proper commit messages as well as produce atomic commts.
It drives me nuts to see 3 commits named 'Update CHANGELOG.md'  or related

2020-11-06 09:06 UTC, phil-davis commented on lib/Sabre/OpenIdSabreAuthBackend.php
> +			try {
I guess that people are making online changes in GitHub with the online editor, and not bothering to change the default commit message. It happens all the time in the docs repo also - annoying.

2020-11-06 09:07 UTC, micbar commented on lib/Sabre/OpenIdSabreAuthBackend.php
> +			try {
disable web editing?

2020-11-06 09:08 UTC, DeepDiver1975 commented on lib/Sabre/OpenIdSabreAuthBackend.php
> +			try {
if possible - yes - web edit was the worst invention ever ...

2020-11-06 09:13 UTC, merged

2020-11-06 09:13 UTC, phil-davis commented on lib/Sabre/OpenIdSabreAuthBackend.php
> +			try {
IMO people should learn how to `git clone` `git fetch` `git pull` `git checkout` `git checkout -b new-branch` `git add` `git commit -m "A decent commit message"` `git push` and so on. i.e. work locally on changes, use a local editor/IDE and pull/push from/to GitHub.

But often these are non-developers and they just want to change some words in text files like changelog and readme. So the online GitHub editor is easy. But of course, you then get a bunch of commits fixing bits of content, typos, grammar, and "nobody" knows how to squash into into a set of logical commits.