Add config option to allow basic auth only for guests
owncloud/openidconnect pull request #253
Opened 2022-09-26 12:14 UTC by jvillafanez

Guests will be able to access ownCloud using basic auth, but other users will need to access through other mechanisms such as oidc.

## Description
The new `openid-connect.basic_auth_guest_only` config option only allows guests to be able to log in using basic auth. Other users will need to use another auth mechanisms (such as oidc)

Note that the users can still log in with ANY OTHER auth mechanism available, not just oidc. It's expected that oidc is the only alternative though.

**NOTE**: minimum OC version raised to 10.4 in order to use the `UserTypeHelper` to detect guest users.

**To be checked**:
* remember me feature doesn't work with this app. It might still be useful for the guests though. We might need to disable the feature from the app info.
* App password aren't expected to work

## Related Issue
https://github.com/owncloud/enterprise/issues/5295

## Motivation and Context

## How Has This Been Tested?
Manually tested:
1. Setup:
    * Keycloak with LDAP connected
    * Guest app installed
    * user_ldap app installed and connected to the same server which keycloak is connected to.
    * openidconnect app connected to keycloak
2. Set `'openid-connect.basic_auth_guest_only' => true` in the config.php file
3. Ensure you can access with userA through keycloak using openidconnect (using the alternative login in the login page)
4. Ensure you can access with a guest user using username and password in the ownCloud's login page
5. Ensure you cannot access with userA through the ownCloud's login page

![Screenshot from 2022-09-26 14-06-15](https://user-images.githubusercontent.com/1477829/192272150-89a228a5-f99a-41df-9302-25c817fde3a5.png)

**Note**: Users (except guests) MUST also use a different auth mechanism (such as oidc) in order to access to the webdav interface. This might affect mobile and desktop clients. It's expected to work, but not tested yet.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Unit tests

2022-09-26 12:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/openidconnect?pullRequest=253) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/openidconnect?pullRequest=253) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/openidconnect?pullRequest=253) it.</sub>

2022-09-26 14:05 UTC, DeepDiver1975 requested changes
- [ ] testable via unit test ?
- [ ] :robot: is :red_circle:

2022-09-26 14:05 UTC, DeepDiver1975 commented on lib/LoginChecker.php
> +		if (!$this->config->getSystemValue('openid-connect.basic_auth_guest_only', false)) {
Maybe only add the listener if config states ...... but minor detail .....

2022-09-27 10:29 UTC, DeepDiver1975 approved these changes

2022-09-28 07:57 UTC, pmaier1 commented
Needs documentation @mmattel

2022-09-28 11:05 UTC, merged

2022-09-28 12:21 UTC, ChrisEdS commented
Needs also translation for the new error message?

<img width="434" alt="image" src="https://user-images.githubusercontent.com/33026403/192777183-a3ebf80f-35c0-42ff-8e65-7e9ab7f99ac4.png">

2022-09-28 13:46 UTC, DeepDiver1975 commented
indeed - until today we don't have any translations .... I can take care